name: Test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python:
        - "3.8"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .
    - name: Test Bloom Filter
      run: PYTHONPATH=src python3 test/test_bloom_filter.py
    - name: Test Cuckoo Filter
      run: PYTHONPATH=src python3 test/test_cuckoo_filter.py
    - name: Test Vaccum Filter
      run: PYTHONPATH=src python3 test/test_vacuum_filter.py
    - name: Test Xor Filter
      run: PYTHONPATH=src python3 test/test_xor_filter.py

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: pip install flake8
    - name: Test
      run: flake8 --ignore=W503 src test
